//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        public patient()
        {
            this.rendez_vous = new HashSet<rendez_vous>();
        }
    
        public long id_patient { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string tel { get; set; }
        public string adresse { get; set; }
        public string mutuel { get; set; }
        public string observation { get; set; }
    
        public virtual ICollection<rendez_vous> rendez_vous { get; set; }
    }
}
