//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilisteur
    {
        public utilisteur()
        {
            this.consultations = new HashSet<consultation>();
            this.rendez_vous = new HashSet<rendez_vous>();
        }
    
        public long id_user { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string tel { get; set; }
        public string role { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<consultation> consultations { get; set; }
        public virtual ICollection<rendez_vous> rendez_vous { get; set; }
    }
}
