//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionBibliothique
{
    using System;
    using System.Collections.Generic;
    
    public partial class eleve
    {
        public eleve()
        {
            this.demandes = new HashSet<demande>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public Nullable<System.DateTime> datenaiss { get; set; }
        public Nullable<int> id_classe { get; set; }
    
        public virtual ICollection<demande> demandes { get; set; }
    }
}
