//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionBibliothique
{
    using System;
    using System.Collections.Generic;
    
    public partial class livre
    {
        public livre()
        {
            this.demandes = new HashSet<demande>();
        }
    
        public int id { get; set; }
        public string titre { get; set; }
        public string auteur { get; set; }
        public string edition { get; set; }
        public string photo { get; set; }
        public Nullable<int> id_cat { get; set; }
        public Nullable<bool> disponibilite { get; set; }
        public Nullable<int> quantite { get; set; }
    
        public virtual ICollection<demande> demandes { get; set; }
    }
}
